"""add template_id to sms_messages

Revision ID: 8ec65b500d17
Revises: fb19c71c682d
Create Date: 2026-08-17 15:12:21.233130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec65b500d17'
down_revision: Union[str, Sequence[str], None] = 'fb19c71c682d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_messages', sa.Column('template_id', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_messages', 'template_id')
    # ### end Alembic commands ###
