"""create sms_messages table

Revision ID: fb19c71c682d
Revises: 
Create Date: 2026-07-06 09:03:27.993779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'fb19c71c682d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('label', sa.Enum('LEGIT', 'PHISHING_CREDENTIAL', 'PHISHING_REVERSAL_SCAM', 'FAKE_AGENT', 'PRIZE_SCAM', 'OTHER_FRAUD', name='smslabel', native_enum=False, length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('predicted_class', sa.Enum('LEGIT', 'PHISHING_CREDENTIAL', 'PHISHING_REVERSAL_SCAM', 'FAKE_AGENT', 'PRIZE_SCAM', 'OTHER_FRAUD', name='smslabel', native_enum=False, length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_messages')
    # ### end Alembic commands ###
